add select with value in schema
hwdtech/smartforms pull request #3
Opened 2017-06-29 11:00 UTC by sln84

2017-06-29 12:20 UTC, 102 requested changes

2017-06-29 12:20 UTC, 102 commented on examples/combine_schema_with_form.js
> +      var elementName = element.name;
We prefer using `const` instead of `var` & `let`, if it's possible

2017-06-29 12:20 UTC, 102 commented on examples/forms/select_with_value_in_schema.json
> +}
Text files should end with newline symbols

[Further reading](https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline)

2017-06-29 12:23 UTC, IgorZiegler commented on examples/combine_schema_with_form.js
> +      element.values.forEach(function(item) {
Use arrow functions

2017-06-29 12:23 UTC, IgorZiegler commented on examples/combine_schema_with_form.js
> +      var activeElement = element.values.filter(function(item) {
Use arrow functions

2017-06-29 12:30 UTC, IgorZiegler commented on examples/index.js
>    $providersContainer.on('click', '.receipt-modal-initial-button a', function (e) {
Use arrow functions

2017-06-29 12:30 UTC, IgorZiegler commented on examples/index.js
> +  $providersWithSchemaContainer.on('click', '.modal-initial-button a', function (e) {
Use arrow functions

2017-06-29 12:30 UTC, IgorZiegler commented on frontend/blocks/select/select_with_value.js
> +    options.each(function (i) {
Use arrow functions

2017-06-29 12:30 UTC, IgorZiegler commented on frontend/blocks/select/select_with_value.js
> +    const arr = options.map(function () {
Use arrow functions

2017-06-29 12:30 UTC, IgorZiegler commented on examples/combine_schema_with_form.js
> +    const schema = JSON.parse(JSON.stringify(schemaJson));
Use cloneDeep

2017-06-29 12:30 UTC, IgorZiegler commented on examples/combine_schema_with_form.js
> +    const schema = JSON.parse(JSON.stringify(schemaJson));
Use cloneDeep

2017-06-29 12:57 UTC, IgorZiegler commented on examples/combine_schema_with_form.js
> +      const activeElement = element.values.filter(item => {
```
const activeElement = element.values.filter(item => item.isActive === true)
```

2017-06-29 12:57 UTC, IgorZiegler commented on examples/combine_schema_with_form.js
> +        selectElement.values.push({name: name, value: value});
Use lodash pick method. This will help get rid of unnecessary variables

2017-06-29 13:03 UTC, IgorZiegler commented on examples/combine_schema_with_form.js
> +        selectElement.values.push({name: name, value: value});
Remove unnecessary variables `name` and `value`
```
selectElement.values.push({name: item.name, value: item.value});
```

2017-06-29 13:34 UTC, 102 commented
@sln84 as far as I understand, the only difference in code between `select/select.js` and `select/select_with_value.js` are class and component names. Are you able to fulfil required functionality without creating a new component?

2017-06-30 07:12 UTC, sln84 commented on frontend/blocks/select/select_with_value.js
> +    const arr = options.map(function () {
fix

2017-06-30 07:12 UTC, sln84 commented on frontend/blocks/select/select_with_value.js
> +    options.each(function (i) {
fix

2017-06-30 07:12 UTC, sln84 commented on examples/combine_schema_with_form.js
> +      const activeElement = element.values.filter(item => {
fix

2017-06-30 07:12 UTC, sln84 commented on examples/combine_schema_with_form.js
> +        selectElement.values.push({name: name, value: value});
fix

2017-06-30 07:19 UTC, sln84 commented
Yes, the only difference in code between select/select.js and select/select_with_value.js are class and component names. But handlers of these classes in our project differ. The handler for select/select_with_value.js uses other number of parameters and a way of their transfer to a form than the handler for a select/select.js. To use the existing component, it is necessary to change handler for it and the existing forms. But it contradicts SOLID.

But maybe you know more graceful decision?

2017-06-30 08:51 UTC, sln84 commented on examples/combine_schema_with_form.js
> +      var elementName = element.name;
fix

2017-06-30 08:53 UTC, sln84 commented on examples/combine_schema_with_form.js
> +      var activeElement = element.values.filter(function(item) {
fix

2017-06-30 08:54 UTC, sln84 commented on examples/combine_schema_with_form.js
> +      element.values.forEach(function(item) {
fix

2017-06-30 09:51 UTC, sln84 commented on frontend/blocks/select/select_with_value.js
> +    options.each(function (i) {
fix

2017-06-30 09:51 UTC, sln84 commented on frontend/blocks/select/select_with_value.js
> +    const arr = options.map(function () {
fix

2017-06-30 09:55 UTC, IgorZiegler commented on examples/index.js
> +        var readyForm = combiner.getForm(providerSchema, data, $globalConfig);
Should be const instead of var

2017-06-30 12:21 UTC, closed without merging